server:
  port : 8087
  forward-headers-strategy: framework

network-store-server:
   base-uri: http://localhost:8080
   preloading-strategy: COLLECTION

network-geo-data:
  iterations : 5

cassandra-keyspace: geo_data

