server:
  forward-headers-strategy: framework

spring:
  profiles:
    active: default,local

network-store-server:
   preloading-strategy: COLLECTION

network-geo-data:
  iterations : 5

cassandra-keyspace: geo_data

